#!/usr/bin/env node
// Build the compact INDEX.md from SKILL.md frontmatter.
// Reads every skills/<category>/<name>/SKILL.md, extracts name + description + provenance,
// writes skills/INDEX.md as a single markdown table the model can scan cheaply.

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_ROOT = join(__dirname, "..", "skills");

function parseFrontmatter(src) {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([a-z_]+):\s*(.*)$/i);
    if (!kv) continue;
    const [, key, val] = kv;
    fm[key] = val.replace(/^["']|["']$/g, "").trim();
  }
  return fm;
}

async function walk(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(p, out);
    } else if (entry.name === "SKILL.md") {
      out.push(p);
    }
  }
  return out;
}

const files = await walk(SKILLS_ROOT);
const skills = [];

for (const file of files) {
  const rel = file
    .substring(SKILLS_ROOT.length + 1)
    .replace(/\\/g, "/")
    .replace(/\/SKILL\.md$/, "");
  const [category, name] = rel.split("/");
  const src = await readFile(file, "utf8");
  const fm = parseFrontmatter(src);
  if (!fm) continue;
  skills.push({
    category,
    name: fm.name || name,
    description: fm.description || "",
    provenance: fm.provenance || "unknown",
    pinned: fm.pinned === "true",
    version: fm.version || "0.0.0",
  });
}

skills.sort((a, b) => {
  if (a.category !== b.category) return a.category.localeCompare(b.category);
  return a.name.localeCompare(b.name);
});

const lines = [
  "# Skills index",
  "",
  "> Auto-generated by `scripts/build-index.mjs`. Do not edit by hand.",
  "> Compact lookup table for skill activation — the model reads this to decide which full SKILL.md to load.",
  "",
  `Total skills: ${skills.length}`,
  "",
  "| Pin | Category | Name | Provenance | v | Description |",
  "|-----|----------|------|------------|---|-------------|",
];

for (const s of skills) {
  const pin = s.pinned ? "📌" : "";
  lines.push(
    `| ${pin} | ${s.category} | \`${s.name}\` | ${s.provenance} | ${s.version} | ${s.description} |`
  );
}

const out = lines.join("\n") + "\n";
await writeFile(join(SKILLS_ROOT, "INDEX.md"), out, "utf8");
console.log(`Wrote ${join(SKILLS_ROOT, "INDEX.md")} with ${skills.length} skills.`);
